/* Dades del seguiment integral de Social360 (document de 28 de setembre de 2026).
   Sense noms de persones ni detalls de seguretat. Els camps buits del document són null i es mostren com a «No informat». */
window.S360 = {
 "fitxes": [
  {
   "eix": "e1",
   "codi": "1.1",
   "titol": "Accés autenticat a l'aplicació web",
   "nota": 10,
   "impr": "Sí",
   "risc": "Sense",
   "desc": null,
   "situacio": null,
   "plecs": null,
   "eines": "Identificació digital (idCAT, Cl@ve) - Integració amb VALid - Es fa servir a la seu i a tràmits",
   "docs": "Funcionament VALid",
   "obs": null,
   "id": "f-1-1"
  },
  {
   "eix": "e1",
   "codi": "1.2",
   "titol": "Auto-obertura de la carpeta social",
   "nota": 10,
   "impr": "Sí",
   "risc": "Sense",
   "desc": "Permet que qualsevol ciutadà empadronat a Mataró, mitjançant identificació digital, pugui obrir un expedient social personal.",
   "situacio": null,
   "plecs": "Auto-obertura de l’expedient social a través d’identificació digital.",
   "eines": null,
   "docs": null,
   "obs": null,
   "id": "f-1-2"
  },
  {
   "eix": "e1",
   "codi": "1.3",
   "titol": "Edició i modificació de dades personals",
   "nota": 10,
   "impr": "Sí",
   "risc": "Sense",
   "desc": "Els usuaris poden modificar dades com telèfon, correu electrònic, adreça i fotografia.",
   "situacio": null,
   "plecs": "Edició i modificació de dades personals dins la Carpeta Social.",
   "eines": "Integració territori i persones",
   "docs": null,
   "obs": null,
   "id": "f-1-3"
  },
  {
   "eix": "e1",
   "codi": "1.4.1",
   "titol": "Accés a documents personals del DMS",
   "nota": 10,
   "impr": "Sí",
   "risc": "Sense",
   "desc": "Consulta i descàrrega de documents propis i sol·licituds registrades en l’expedient.",
   "situacio": null,
   "plecs": "Accés a documents personals emmagatzemats a la Carpeta Social.",
   "eines": "Accés al gestor de documents (DMS)",
   "docs": "Interfície accés al DMS",
   "obs": null,
   "id": "f-1-4-1"
  },
  {
   "eix": "e1",
   "codi": "1.4.2",
   "titol": "Accés a documents personals a GTM",
   "nota": 0,
   "impr": "No",
   "risc": "Baix",
   "desc": "Consulta i descàrrega de documents propis pujats a GTM. Caldrà revisar si es viable depenent de com s'identifiquin els documents a GTM, ja sigui via el codi de procés o les seves metadades.",
   "situacio": "Pendent concreció",
   "plecs": "Accés a documents personals emmagatzemats a la Carpeta Social.",
   "eines": "Accés al gestor de documents (DMS)",
   "docs": "Pendent de valorar si és possible depenent de com s'identifiquin els documents a GTM  i implementar si és possible",
   "obs": null,
   "id": "f-1-4-2"
  },
  {
   "eix": "e1",
   "codi": "1.5.1",
   "titol": "Consulta de l’estat de tràmits plataforma Ajuntament",
   "nota": 5,
   "impr": "Sí",
   "risc": "Baix",
   "desc": "Els usuaris poden veure l’estat dels tràmits iniciats i la informació del professional referent.",
   "situacio": "Pendent concreció",
   "plecs": "Consulta de l’estat de tràmits i gestions de Serveis Socials.",
   "eines": "Plataforma de tràmits corporativa",
   "docs": "Consulta tràmits i possibilitat d'obrir una pestanya per gestionar el tràmit per part del ciutadà",
   "obs": null,
   "id": "f-1-5-1"
  },
  {
   "eix": "e1",
   "codi": "1.5.2",
   "titol": "Consulta de l’estat de tràmits/expedients plataforma GTM",
   "nota": 0,
   "impr": "Sí",
   "risc": "Baix",
   "desc": "Els usuaris poden veure l’estat dels tràmits iniciats i la informació del professional referent.",
   "situacio": null,
   "plecs": "Consulta de l’estat de tràmits i gestions de Serveis Socials.",
   "eines": "Plataforma d'expedients GTM",
   "docs": "Pendent d'implementar",
   "obs": null,
   "id": "f-1-5-2"
  },
  {
   "eix": "e1",
   "codi": "1.6",
   "titol": "Sol·licitud de cita prèvia",
   "nota": 0,
   "impr": "Sí",
   "risc": "Baix",
   "desc": "Permet demanar cita amb Serveis Socials o altres organismes vinculats.",
   "situacio": "Planificat",
   "plecs": "Sol·licitud de cita prèvia amb serveis socials i altres organismes.",
   "eines": "Gestió de calendari - Integració amb Gestorn",
   "docs": null,
   "obs": null,
   "id": "f-1-6"
  },
  {
   "eix": "e1",
   "codi": "1.7",
   "titol": "Agenda personal integrada",
   "nota": 0,
   "impr": "Sí",
   "risc": "Baix",
   "desc": "Gestió de cites, tallers, terminis de requeriments i caducitat de recursos.",
   "situacio": "Planificat",
   "plecs": "Agenda personal integrada dins la Carpeta Social.",
   "eines": "Gestió de calendari",
   "docs": null,
   "obs": null,
   "id": "f-1-7"
  },
  {
   "eix": "e1",
   "codi": "1.8",
   "titol": "Notificacions i comunicació telemàtica",
   "nota": 10,
   "impr": "Sí",
   "risc": "Sense",
   "desc": "Bústia personal per rebre i enviar missatges amb el referent social o el servei en general.",
   "situacio": null,
   "plecs": "Comunicació telemàtica i notificacions dins la Carpeta Social.",
   "eines": "Sistema de notificacions SMS/email - No es fa ús",
   "docs": "Procediments per l'enviament de SMS i correus des del'arquitectura corporativa",
   "obs": null,
   "id": "f-1-8"
  },
  {
   "eix": "e1",
   "codi": "1.9",
   "titol": "Multi-idioma",
   "nota": 0,
   "impr": null,
   "risc": "No classificat",
   "desc": "Interfície disponible inicialment en català i castellà, amb possibilitat d’ampliació.",
   "situacio": null,
   "plecs": "La interfície d’usuari suportarà múltiples idiomes.",
   "eines": "No contempla integracions",
   "docs": null,
   "obs": null,
   "id": "f-1-9"
  },
  {
   "eix": "e1",
   "codi": "1.10",
   "titol": "Creació de l'entorn Apache/TOMCAT",
   "nota": 10,
   "impr": "Sí",
   "risc": "Sense",
   "desc": "Implementats els tres entorns:desenvolupament, preproducció i producció. Creació de la cel·la on desplegar l'aplicació basada en Javascript i Angular",
   "situacio": null,
   "plecs": null,
   "eines": null,
   "docs": null,
   "obs": null,
   "id": "f-1-10"
  },
  {
   "eix": "e1",
   "codi": "1.11",
   "titol": "Implementació del sistema de control de versions",
   "nota": 5,
   "impr": "Sí",
   "risc": "Baix",
   "desc": "Sistema SVN de versionat corporatiu",
   "situacio": null,
   "plecs": null,
   "eines": null,
   "docs": null,
   "obs": null,
   "id": "f-1-11"
  },
  {
   "eix": "e1",
   "codi": "1.12",
   "titol": "Adequació l'Esquema Nacional de Seguretat",
   "nota": 10,
   "impr": "Sí",
   "risc": "Sense",
   "desc": "Tema sobrevingut d'adequació a l'ENS: definició dels entorns de treball (desenvolupament, preproducció i producció), accés segur als servidors i gestió de credencials",
   "situacio": null,
   "plecs": null,
   "eines": null,
   "docs": null,
   "obs": null,
   "id": "f-1-12"
  },
  {
   "eix": "e1",
   "codi": "1.13",
   "titol": "Prova pilot",
   "nota": 0,
   "impr": "Sí",
   "risc": "Alt",
   "desc": null,
   "situacio": null,
   "plecs": null,
   "eines": null,
   "docs": null,
   "obs": null,
   "id": "f-1-13"
  },
  {
   "eix": "e2",
   "codi": "2.1",
   "titol": "Revisió funcionalitats de SocialMat",
   "nota": 10,
   "impr": "Sí",
   "risc": "Sense",
   "desc": "Revisió de les funcionalitats de l'aplicació SocialMat",
   "situacio": "No s'evoluciona l'aplicació actual i es fa un nou desenvolupament",
   "plecs": "Implementació de canvis en l'aplicació existent SocialMat en base a un anàlisi previ ja realitzat",
   "eines": "Oracle APEX",
   "docs": null,
   "obs": null,
   "id": "f-2-1"
  },
  {
   "eix": "e2",
   "codi": "2.1.1",
   "titol": "Autenticació corporativa i LDAP corporatiu",
   "nota": 10,
   "impr": "Sí",
   "risc": "Sense",
   "desc": "Autenticació amb l'autenticació via  corporativa",
   "situacio": "Operatiu",
   "plecs": null,
   "eines": "Directori actiu i seguretat corporativa",
   "docs": null,
   "obs": null,
   "id": "f-2-1-1"
  },
  {
   "eix": "e2",
   "codi": "2.1.2",
   "titol": "Funcionalitat pendent de concretar",
   "nota": null,
   "impr": null,
   "risc": null,
   "desc": null,
   "situacio": null,
   "plecs": null,
   "eines": null,
   "docs": null,
   "obs": null,
   "id": "f-2-1-2"
  },
  {
   "eix": "e2",
   "codi": "2.1.3",
   "titol": "Funcionalitat pendent de concretar",
   "nota": null,
   "impr": null,
   "risc": null,
   "desc": null,
   "situacio": null,
   "plecs": null,
   "eines": null,
   "docs": null,
   "obs": null,
   "id": "f-2-1-3"
  },
  {
   "eix": "e2",
   "codi": "2.1.4",
   "titol": "Funcionalitat pendent de concretar",
   "nota": null,
   "impr": null,
   "risc": null,
   "desc": null,
   "situacio": null,
   "plecs": null,
   "eines": null,
   "docs": null,
   "obs": null,
   "id": "f-2-1-4"
  },
  {
   "eix": "e2",
   "codi": "2.2",
   "titol": "Interoperabilitat aplicacions APEX actuals",
   "nota": 8,
   "impr": "Sí",
   "risc": "Molt baix",
   "desc": "Accedir a les aplicacions APEX existents de forma transparent sense tornar a validar. L'aplicació comparteix Workspace per permetre la integració màxima amb l'ecosistema actual d'aplicacions de l'àmbit social desenvolupades sobre APEX.",
   "situacio": "Es fa una prova de concepte per garantir la viabilitat de l'autenticació compartida amb èxit. Un cop validat s'a",
   "plecs": "Garantir la interoperabilitat de Social360 amb les aplicacions desenvolupades sobre Apex",
   "eines": "eSAD, EAIA, històrics, Sensellarisme,emergència habitatge, registre entrada edificis, reserva espais, Oficina Cures",
   "docs": null,
   "obs": "La situació actual acaba amb «Un cop validat s’a» a la font; la frase resta pendent de concretar.",
   "id": "f-2-2"
  },
  {
   "eix": "e2",
   "codi": "2.2.1",
   "titol": "eSAD",
   "nota": 5,
   "impr": "Sí",
   "risc": "Molt baix",
   "desc": "Aplicació en producció",
   "situacio": "Pendent",
   "plecs": null,
   "eines": null,
   "docs": null,
   "obs": null,
   "id": "f-2-2-1"
  },
  {
   "eix": "e2",
   "codi": "2.2.2",
   "titol": "EAIA",
   "nota": 5,
   "impr": "Sí",
   "risc": "Molt baix",
   "desc": "Aplicació en producció",
   "situacio": "Pendent",
   "plecs": null,
   "eines": null,
   "docs": null,
   "obs": null,
   "id": "f-2-2-2"
  },
  {
   "eix": "e2",
   "codi": "2.2.3",
   "titol": "Històric de Benestar Social",
   "nota": 10,
   "impr": "Sí",
   "risc": "Sense",
   "desc": "Aplicació en producció",
   "situacio": "Prova de concepte amb èxit",
   "plecs": null,
   "eines": null,
   "docs": null,
   "obs": null,
   "id": "f-2-2-3"
  },
  {
   "eix": "e2",
   "codi": "2.2.4",
   "titol": "Sensellarisme",
   "nota": 10,
   "impr": "Sí",
   "risc": "Sense",
   "desc": "Aplicació en producció",
   "situacio": "Prova de concepte amb èxit",
   "plecs": null,
   "eines": null,
   "docs": null,
   "obs": null,
   "id": "f-2-2-4"
  },
  {
   "eix": "e2",
   "codi": "2.2.5",
   "titol": "Emergència Habitacional",
   "nota": 5,
   "impr": "Sí",
   "risc": "Molt baix",
   "desc": "Aplicació en producció",
   "situacio": "Pendent",
   "plecs": null,
   "eines": null,
   "docs": null,
   "obs": null,
   "id": "f-2-2-5"
  },
  {
   "eix": "e2",
   "codi": "2.2.6",
   "titol": "Registre Entrada Edificis",
   "nota": 5,
   "impr": "Sí",
   "risc": "Molt baix",
   "desc": "Aplicació en producció",
   "situacio": "Pendent",
   "plecs": null,
   "eines": null,
   "docs": null,
   "obs": null,
   "id": "f-2-2-6"
  },
  {
   "eix": "e2",
   "codi": "2.2.7",
   "titol": "Reserva Espais",
   "nota": 5,
   "impr": "Sí",
   "risc": "Molt baix",
   "desc": "Aplicació en producció",
   "situacio": "Pendent",
   "plecs": null,
   "eines": null,
   "docs": null,
   "obs": null,
   "id": "f-2-2-7"
  },
  {
   "eix": "e2",
   "codi": "2.2.8",
   "titol": "Oficina Cures",
   "nota": 5,
   "impr": "Sí",
   "risc": "Molt baix",
   "desc": "Aplicació en producció",
   "situacio": "Pendent",
   "plecs": null,
   "eines": null,
   "docs": null,
   "obs": null,
   "id": "f-2-2-8"
  },
  {
   "eix": "e2",
   "codi": "2.3",
   "titol": "Espai de diagnosi social individual, familiar i comunitari",
   "nota": 2,
   "impr": "Sí",
   "risc": "Alt",
   "desc": "Eina per avaluació i diagnosi de situacions individuals, familiars i comunitàries amb tests digitalitzats.",
   "situacio": "No està implementada, però es disposa de prototip operatiu",
   "plecs": "Espai per realitzar diagnòstics digitals dins l’expedient social.",
   "eines": "Dependria de l'eina (a revisar) / No contempla",
   "docs": null,
   "obs": null,
   "id": "f-2-3"
  },
  {
   "eix": "e2",
   "codi": "2.4",
   "titol": "Espai de registre i seguiment d’intervencions individuals, familiars, grupals i comunitàries",
   "nota": 2,
   "impr": "Sí",
   "risc": "Alt",
   "desc": "Eina per documentar i fer seguiment d’intervencions en expedients individuals, familiars o grupals.",
   "situacio": null,
   "plecs": "Registre d’intervencions tècniques dins l’expedient social.",
   "eines": "No contempla integracions",
   "docs": null,
   "obs": null,
   "id": "f-2-4"
  },
  {
   "eix": "e2",
   "codi": "2.5",
   "titol": "Espais de treball integral entre diferents agents socials",
   "nota": 0,
   "impr": "Sí",
   "risc": "Alt",
   "desc": "Accés compartit per a agents socials externs (sanitat, ocupació, seguretat, etc.) amb informació limitada.",
   "situacio": null,
   "plecs": "Accés restringit per a agents externs per a la consulta i introducció de dades.",
   "eines": "Accés web amb perfils restringits, API REST",
   "docs": null,
   "obs": null,
   "id": "f-2-5"
  },
  {
   "eix": "e2",
   "codi": "2.6",
   "titol": "Gestió i control de serveis externalitzats",
   "nota": 0,
   "impr": "Sí",
   "risc": "Alt",
   "desc": "Eina per facilitar la introducció de dades de serveis prestats per entitats externes.",
   "situacio": null,
   "plecs": "Control i introducció de dades per part d’empreses externes.",
   "eines": "Portal de gestió per a entitats externes, API REST",
   "docs": null,
   "obs": null,
   "id": "f-2-6"
  },
  {
   "eix": "e2",
   "codi": "2.7",
   "titol": "Biblioteca documental",
   "nota": 10,
   "impr": "Sí",
   "risc": "Sense",
   "desc": "Repositori centralitzat per als documents generats durant la intervenció social.",
   "situacio": null,
   "plecs": "Espai de documents vinculats a l’expedient social.",
   "eines": "Gestor documental (DMS)",
   "docs": null,
   "obs": null,
   "id": "f-2-7"
  },
  {
   "eix": "e2",
   "codi": "2.8",
   "titol": "Comunicació i notificacions amb persones usuàries",
   "nota": 2,
   "impr": "Sí",
   "risc": "Baix",
   "desc": "Sistema integrat per enviar notificacions o missatges als usuaris de Serveis Socials.",
   "situacio": "Pendent concreció",
   "plecs": "Enviament de notificacions telemàtiques als usuaris.",
   "eines": "Sistema de notificacions SMS/email, API REST",
   "docs": null,
   "obs": null,
   "id": "f-2-8"
  },
  {
   "eix": "e2",
   "codi": "2.9",
   "titol": "Autoritzacions i permisos per rols",
   "nota": 10,
   "impr": "Sí",
   "risc": "Sense",
   "desc": "Gestió de les autoritzacions des diferents rols",
   "situacio": "S'adopta el sistema d'autoritzacions corporatiu i es fa una prova de concepte per securitzar en base a tabs o \"pestanyes\" que valida el sistema",
   "plecs": "Integració amb el sistema de login del Departament de Drets Socials.",
   "eines": "SSO (Single Sign-On), LDAP, OAuth2",
   "docs": null,
   "obs": null,
   "id": "f-2-9"
  },
  {
   "eix": "e2",
   "codi": "2.10",
   "titol": "Registre d’activitat i traçabilitat",
   "nota": 10,
   "impr": "Sí",
   "risc": "Baix",
   "desc": "Logs de sistema per auditar accessos i modificacions a les dades.",
   "situacio": "Incorporació de  dades d'auditoria a les taules",
   "plecs": "Traçabilitat d’accessos i modificacions per seguretat.",
   "eines": "Logs centralitzats, SIEM (Security Information and Event Management)",
   "docs": null,
   "obs": null,
   "id": "f-2-10"
  },
  {
   "eix": "e2",
   "codi": "2.11",
   "titol": "Serveis en el núvol",
   "nota": null,
   "impr": null,
   "risc": null,
   "desc": null,
   "situacio": null,
   "plecs": "L'empresa adjudicatària prepararà Social360 per a una eventual migració al núvol, prioritzant la portabilitat i la compatibilitat entre diferents plataformes del núvol",
   "eines": null,
   "docs": null,
   "obs": null,
   "id": "f-2-11"
  },
  {
   "eix": "e3",
   "codi": null,
   "titol": "Bus de serveis",
   "nota": null,
   "impr": "Sí",
   "risc": "Mig",
   "desc": "Arquitectura preparada que caldrà adaptar en funció del proveïdor",
   "situacio": null,
   "plecs": "Garantir que el bus de serveis estigui adequadament integrat amb els sistemes existents, incloent",
   "eines": null,
   "docs": null,
   "obs": "El text dels plecs acaba amb «incloent»; la continuació no està informada.",
   "id": "f-bus"
  },
  {
   "eix": "e3",
   "codi": "3.1",
   "titol": "Bus de serveis - Integració de sistemes 1",
   "nota": 5,
   "impr": "Sí",
   "risc": "Baix",
   "desc": null,
   "situacio": "Ja disposem d'integracions fetes, però caldrà concretar",
   "plecs": null,
   "eines": "Via Oberta",
   "docs": "Procediments per accedir a Via Oberta - Interfícies per a que Social 360 es connecti a Via Oberta",
   "obs": null,
   "id": "f-3-1",
   "sub": "Via Oberta"
  },
  {
   "eix": "e3",
   "codi": "3.2",
   "titol": "Bus de serveis - Integració de sistemes 2",
   "nota": 0,
   "impr": "No",
   "risc": "Alt",
   "desc": null,
   "situacio": "Pendent contacte via Generalitat",
   "plecs": null,
   "eines": "Jade",
   "docs": "Pendent",
   "obs": null,
   "id": "f-3-2",
   "sub": "Jade"
  },
  {
   "eix": "e3",
   "codi": "3.3",
   "titol": "Bus de serveis - Integració de sistemes 3",
   "nota": 5,
   "impr": "Sí",
   "risc": "Mig",
   "desc": null,
   "situacio": "Lliurada documentació de l'API que caldrà avaluar.",
   "plecs": null,
   "eines": "Gestorn",
   "docs": "Integració amb Ubintia",
   "obs": null,
   "id": "f-3-3",
   "sub": "Gestorn"
  },
  {
   "eix": "e3",
   "codi": "3.4",
   "titol": "Bus de serveis - Integració de sistemes 4",
   "nota": 0,
   "impr": "No",
   "risc": "Mig",
   "desc": null,
   "situacio": "Lliurada documentació de l'API que caldrà avaluar.",
   "plecs": null,
   "eines": "eQualiment",
   "docs": "Pendent",
   "obs": null,
   "id": "f-3-4",
   "sub": "eQualiment"
  },
  {
   "eix": "e3",
   "codi": "3.5",
   "titol": "Bus de serveis - Integració de sistemes 5",
   "nota": 0,
   "impr": "No",
   "risc": "Alt",
   "desc": null,
   "situacio": "Pendent contacte via Generalitat",
   "plecs": null,
   "eines": "Teleassistència",
   "docs": "Pendent",
   "obs": null,
   "id": "f-3-5",
   "sub": "Teleassistència"
  },
  {
   "eix": "e3",
   "codi": "3.6",
   "titol": "Bus de serveis - Integració de sistemes 6",
   "nota": 0,
   "impr": "No",
   "risc": "Baix",
   "desc": null,
   "situacio": "No és propi, però disposem de les dades",
   "plecs": null,
   "eines": "GTM/portasignatures",
   "docs": "Procediments per accedir a GTM",
   "obs": null,
   "id": "f-3-6",
   "sub": "GTM/portasignatures"
  },
  {
   "eix": "e3",
   "codi": "3.7",
   "titol": "Bus de serveis - Integració de sistemes 7",
   "nota": 0,
   "impr": "No",
   "risc": "Baix",
   "desc": null,
   "situacio": "No és propi, però disposem de les dades",
   "plecs": null,
   "eines": "GEMA",
   "docs": "Procediments per accedir a factures",
   "obs": null,
   "id": "f-3-7",
   "sub": "GEMA"
  },
  {
   "eix": "e3",
   "codi": "3.8",
   "titol": "Bus de serveis - Integració de sistemes 8",
   "nota": 5,
   "impr": "No",
   "risc": "Baix",
   "desc": null,
   "situacio": "Sistema propi",
   "plecs": null,
   "eines": "Tràmits",
   "docs": "Procediments per accedir a tràmits",
   "obs": null,
   "id": "f-3-8",
   "sub": "Tràmits"
  },
  {
   "eix": "e4",
   "codi": "4.1",
   "titol": "Informes i memòries automatitzats",
   "nota": 5,
   "impr": "Sí",
   "risc": "Alt",
   "desc": "Possibilitat de recollir dades tematitzades i agilitzar la generació d’informes de servei mitjançant indicadors predefinits.",
   "situacio": null,
   "plecs": "Elaboració d’informes temàtics i memòries de servei automatitzats: Aquesta funció implicaria la possibilitat de recollir i incorporar dades tematitzades en un informe tipus, així com l’agilització de l’elaboració de memòries de servei, a partir de l’establiment d’indicadors i la recollida i presentació de les dades.",
   "eines": null,
   "docs": null,
   "obs": null,
   "id": "f-4-1"
  },
  {
   "eix": "e4",
   "codi": "4.2",
   "titol": "Extracció automàtica d’indicadors",
   "nota": 3,
   "impr": "Sí",
   "risc": "Alt",
   "desc": "Extracció automatitzada de les dades requerides per RUDEL, GABSS i CCI, minimitzant temps i errors en el traspàs i seguiment.",
   "situacio": null,
   "plecs": "Extracció automatitzada de d’indicadors RUDEL, GABSS I CCI. Implicaria l’extracció automatitzada dels diferents indicadors que es demanen a través de RUDEL, GABSS i Cercles de Comparació Intermunicipal, minimitzant el temps de gestió destinat actualment a aquesta tasca, i afavorint la reducció d’errors en el traspàs de dades entre municipi i organismes supramunicipals, així com el seguiment de les dades incorporades cada any.",
   "eines": null,
   "docs": null,
   "obs": null,
   "id": "f-4-2"
  },
  {
   "eix": "e4",
   "codi": "4.3",
   "titol": "Quadres de Comandament intel·ligents",
   "nota": 3,
   "impr": "Sí",
   "risc": "Alt",
   "desc": "Disseny de quadres interactius amb algoritmes de rastreig i anàlisi descriptiva, incloent-hi “indicadors d’alarma” per a la presa de decisions.",
   "situacio": null,
   "plecs": "Creació de Quadres de Comandament Intel·ligents. Disseny i creació de quadres de comandament intel·ligents no estàtics, que facilitin, a través d’algoritmes de rastreig i anàlisi descriptiu de dades al sistema d’informació, incorporar «indicadors d’alarma» com a mecanismes informatiu clau en la gestió i presa de decisions sobre polítiques públiques.",
   "eines": null,
   "docs": null,
   "obs": null,
   "id": "f-4-3"
  },
  {
   "eix": "e4",
   "codi": "4.4",
   "titol": "Anàlisi descriptiva de dades",
   "nota": 2,
   "impr": "Sí",
   "risc": "Alt",
   "desc": "Espai per a l’explotació de dades massives i la incorporació, total o parcial, d’IA per analitzar relacions entre variables socials i de context.",
   "situacio": null,
   "plecs": "Espais d’anàlisi i explotació de dades de caràcter descriptius. Implicaria la possibilitat de disposar d’un espai d’anàlisi descriptiu i explotació massiva de les dades bàsiques sobre les principals variables socials que es trobin incorporades als expedients individuals i familiars, així com dels registres d’intervenció individual, familiar i comunitari. Tanmateix, el desenvolupament d’anàlisis d’interacció entre aquestes dades i altres variables de context, es farà ús d'intel·ligència artificial, total o parcialment, per automatitzar l'anàlisi de les interrelacions entre les dades socials i de context, augmentant la precisió i eficàcia en l'obtenció de resultats rellevants per a la gestió territorial, per tal d’assolir i millor i major coneixement sobre el desenvolupament social de cada territori.",
   "eines": null,
   "docs": null,
   "obs": null,
   "id": "f-4-4"
  },
  {
   "eix": "e4",
   "codi": "4.5",
   "titol": "Modelatge predictiu de dades",
   "nota": 0,
   "impr": "Sí",
   "risc": "Alt",
   "desc": "Possibilitat de projectar escenaris futurs, integrant IA per analitzar correlacions i millorar la presa de decisions sobre pressupostos i polítiques públiques.",
   "situacio": null,
   "plecs": "Espais d’anàlisi i modelatge de dades de caràcter predictiu. Implicaria la possibilitat d’establir anàlisis enfocats a la projecció d’escenaris d’acord amb les dades recollides fins el moment. Es farà ús d'intel·ligència artificial, total o parcialment, per automatitzar l'anàlisi de les interrelacions entre les dades socials i de context, augmentant la precisió i eficàcia en l'obtenció de resultats rellevants per a la gestió territorial. Aquestes projeccions i prognosis estarien orientades a facilitar i a fer més efectiva la pressa de decisions sobre la gestió de pressupostos i polítiques públiques, potenciant la Interconsulta de dades anonimitzades amb altres administracions, amb l’objectiu d’afavorir l’intercanvi de dades com a eina de coneixement social integral.",
   "eines": null,
   "docs": null,
   "obs": null,
   "id": "f-4-5"
  },
  {
   "eix": "e4",
   "codi": "4.6",
   "titol": "IA en un dels darrers punts",
   "nota": 0,
   "impr": "No",
   "risc": "Alt",
   "desc": "Només caldrà implementar Intel·ligència Artificial de manera total o parcial en un dels dos últims punts d’anàlisi i modelatge.",
   "situacio": null,
   "plecs": "Només caldrà implementar IA en un dels dos darrers punts.",
   "eines": null,
   "docs": null,
   "obs": null,
   "id": "f-4-6"
  },
  {
   "eix": "g",
   "codi": "5.1",
   "titol": "Suport a la multientitat",
   "nota": null,
   "impr": null,
   "risc": null,
   "desc": null,
   "situacio": null,
   "plecs": "Garantir que el sistema Social360 sigui capaç de suportar la gestió multientitat, permetent a diverses entitats utilitzar el sistema de manera compartida",
   "eines": null,
   "docs": null,
   "obs": null,
   "id": "f-5-1"
  },
  {
   "eix": "g",
   "codi": "5.2",
   "titol": "Multinavegador",
   "nota": null,
   "impr": null,
   "risc": null,
   "desc": null,
   "situacio": null,
   "plecs": null,
   "eines": null,
   "docs": null,
   "obs": null,
   "id": "f-5-2"
  },
  {
   "eix": "g",
   "codi": "5.3",
   "titol": "Marc d'interoperabilitat proposat",
   "nota": null,
   "impr": null,
   "risc": null,
   "desc": null,
   "situacio": null,
   "plecs": "En cas que hi hagi dispositius involucrats, caldrà definir conjuntament amb el Departament de Drets Socials els protocols d'integració d'aquests dispositius si el Departament de Drets Socials",
   "eines": null,
   "docs": null,
   "obs": "El text dels plecs acaba amb «si el Departament de Drets Socials»; la condició resta pendent de concretar.",
   "id": "f-5-3"
  },
  {
   "eix": "g",
   "codi": "5.4",
   "titol": "Garantir intercanvi de dades amb el DDS (Departament de Drets Socials)",
   "nota": null,
   "impr": null,
   "risc": null,
   "desc": null,
   "situacio": null,
   "plecs": null,
   "eines": null,
   "docs": null,
   "obs": null,
   "id": "f-5-4"
  },
  {
   "eix": "g",
   "codi": "5.5",
   "titol": "Sistema de login",
   "nota": null,
   "impr": null,
   "risc": null,
   "desc": null,
   "situacio": null,
   "plecs": null,
   "eines": null,
   "docs": null,
   "obs": null,
   "id": "f-5-5"
  },
  {
   "eix": "g",
   "codi": "5.6",
   "titol": "Integració amb persones",
   "nota": null,
   "impr": null,
   "risc": null,
   "desc": "Acordar de l'identificador persona a utilitzar. En un principi hauria de ser l'identificador de les aplicacions corporatives. S'acorda el codi únic de la base de dades i el de padró.",
   "situacio": null,
   "plecs": null,
   "eines": null,
   "docs": null,
   "obs": null,
   "id": "f-5-6"
  },
  {
   "eix": "g",
   "codi": "5.7",
   "titol": "Integració amb territori",
   "nota": null,
   "impr": null,
   "risc": null,
   "desc": "Adoptar l'identificador de les adreces de T-Systems",
   "situacio": null,
   "plecs": null,
   "eines": null,
   "docs": null,
   "obs": null,
   "id": "f-5-7"
  },
  {
   "eix": "g",
   "codi": null,
   "titol": "Prova pilot (global)",
   "nota": null,
   "impr": "Sí",
   "risc": "Mig",
   "desc": null,
   "situacio": null,
   "plecs": null,
   "eines": null,
   "docs": null,
   "obs": null,
   "id": "f-g-pilot"
  },
  {
   "eix": "g",
   "codi": null,
   "titol": "Migració",
   "nota": null,
   "impr": "Sí",
   "risc": "Mig",
   "desc": null,
   "situacio": null,
   "plecs": null,
   "eines": null,
   "docs": null,
   "obs": null,
   "id": "f-g-migracio"
  }
 ],
 "eixos": [
  {
   "id": "e1",
   "nom": "Eix 1",
   "titol": "Implementar la carpeta social"
  },
  {
   "id": "e2",
   "nom": "Eix 2",
   "titol": "Integració de totes les aplicacions d'ús tècnic i administratiu"
  },
  {
   "id": "e3",
   "nom": "Eix 3",
   "titol": "Garantir la interoperabilitat"
  },
  {
   "id": "e4",
   "nom": "Eix 4",
   "titol": "Informes i quadres de comandament"
  },
  {
   "id": "g",
   "nom": "Globals",
   "titol": "Requisits transversals"
  }
 ],
 "dependencies": [
  {
   "nom": "Generalitat i DDS",
   "codis": [
    "3.2",
    "3.5",
    "2.9",
    "5.3",
    "5.4",
    "5.5"
   ],
   "text": "Dependència externa. Contactes pendents per Jade i Teleassistència; requisits d'interoperabilitat, intercanvi de dades i login a concretar. El login corporatiu validat no acredita el login DDS"
  },
  {
   "nom": "GTM i portasignatures",
   "codis": [
    "1.4.2",
    "1.5.2",
    "3.6"
   ],
   "text": "Sistema no propi i interfícies corporatives. Cal validar la identificació i recuperació de documents, l'inventari de tràmits i la seguretat. Consta l'accés a expedients implementat, però 3.6 manté puntuació 0"
  },
  {
   "nom": "Gestorn i Ubintia",
   "codis": [
    "1.6",
    "3.3"
   ],
   "text": "Dependència externa. Documentació de l'API lliurada pendent d'avaluar. En principi ja està integrat; cal confirmar-ne l'abast efectiu"
  },
  {
   "nom": "Jade",
   "codis": [
    "3.2"
   ],
   "text": "Risc Alt i puntuació 0. Contacte via Generalitat pendent. Aplicació web amb enllaç directe (deeplinking), amb incertesa sobre canvis futurs"
  },
  {
   "nom": "eQualiment",
   "codis": [
    "3.4"
   ],
   "text": "Risc Mig i puntuació 0. API lliurada pendent d'avaluar; exploració pendent"
  },
  {
   "nom": "Teleassistència",
   "codis": [
    "3.5"
   ],
   "text": "Risc Alt i puntuació 0. Contacte via Generalitat i exploració pendents"
  },
  {
   "nom": "Via Oberta",
   "codis": [
    "3.1"
   ],
   "text": "Accés mitjançant el sistema i el hub corporatius. Cal concretar interfícies i procediments perquè Social360 s'hi connecti"
  },
  {
   "nom": "GEMA",
   "codis": [
    "3.7"
   ],
   "text": "Sistema no propi. L'Ajuntament farà de hub, sense fer servir els serveis web del proveïdor. Cal accés a factures i tercers; la interfície de factures ja és disponible"
  },
  {
   "nom": "Tràmits",
   "codis": [
    "1.5.1",
    "3.8"
   ],
   "text": "Sistema propi amb interfície disponible. Cal concretar tipologies, permisos, capa de seguretat i accés de la ciutadania"
  },
  {
   "nom": "DMS",
   "codis": [
    "1.4.1",
    "2.7"
   ],
   "text": "Gestor documental corporatiu. Cal decidir quins documents es veuen, la càrrega de documents per part de la ciutadania, les categories i l'adaptació al sistema documental"
  },
  {
   "nom": "VALid i AOC",
   "codis": [
    "1.1"
   ],
   "text": "Servei extern d'identificació. Cal documentar-ne el funcionament i concretar els casos de menors d'edat i l'accés després de la baixa del municipi"
  }
 ]
};
